version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - order
      - payment
      - inventory
      - auth
    networks:
      - app_network

  order:
    build: ./services/order
    container_name: order
    ports:
      - "8001:8001"
    depends_on:
      - auth
      - inventory
      - payment
    networks:
      - app_network

  payment:
    build: ./services/payment
    container_name: payment
    ports:
      - "8002:8002"
    networks:
      - app_network

  inventory:
    build: ./services/inventory
    container_name: inventory
    ports:
      - "8003:8003"
    networks:
      - app_network

  auth:
    build: ./services/auth
    container_name: auth
    ports:
      - "8004:8004"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

